version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "version-one_dictionary"
    AWS_DEFAULT_REGION: "us-east-1"
    ACCOUNT_ID: "309191981503"
    EKS_CLUSTER_NAME: "eks-cb-dev"
    TAG: "latest"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
      - chmod +x skaffold && mv skaffold /usr/local/bin/
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh && ./get_helm.sh
      - pip install awscli --upgrade
  pre_build:
    commands:
      - echo "Authenticating to EKS..."
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME

  build:
    commands:
      - echo "Deploying using Skaffold..."
      - skaffold deploy --images $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG --status-check=true
      - echo "Deployment completed."